version = 0.1
[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "daniele"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yf79lochy3zo"
s3_prefix = "daniele"
region = "eu-central-1"
profile = "test"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
